
/**
Constructor
Do not call Function in Constructor.
*/
class MainPage()
{
	super();

	//TODO:edit here

}
extends AView;


function MainPage*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function MainPage*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function MainPage*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
