
/**
Constructor
Do not call Function in Constructor.
*/
class NavBar()
{
	super();

	//TODO:edit here

}
extends AView;


function NavBar*init(context, evtListener)
{
	super.init(context, evtListener);

	this.header_area.setStyle('position', 'fixed');

};

function NavBar*onInitDone()
{
	super.onInitDone();

	

};

function NavBar*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
